## prometheus.yml ##

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

#rule_files:
#  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'users-service'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
       - targets: ['users-service:8000']
         labels:
          group: 'users-service'

  - job_name: 'products-service'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
       - targets: ['products-service:8001']
         labels:
          group: 'products-service'

  - job_name: 'cadvisor'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
       - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
       - targets: ['node_exporter:9100']
