version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/test.insert.sql:/docker-entrypoint-initdb.d/test.insert.sql
    networks:
      - auction-house

  mongodb:
    image: mongo
    container_name: mongodb_database
    ports:
      - '27017:27017'
    volumes:
      - mongodb_database_test:/data/db
    networks:
      - auction-house

  app_test:
    container_name: app_test
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    restart: on-failure
    volumes:
      - api_test:/usr/src/app/
    depends_on:
      - postgres
      - mongodb
    networks:
      - auction-house

volumes:
  api_test:
  database_postgres_test:
  mongodb_database_test:

networks:
  auction-house: