// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_service.proto

package users_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Balance              float64              `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Birthdate            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetBirthdate() *timestamp.Timestamp {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetUserByIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{1}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateUserRequest struct {
	FirstName            string               `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Birthdate            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetBirthdate() *timestamp.Timestamp {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

type CreateUserReply struct {
	LastId               string   `protobuf:"bytes,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{3}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetLastId() string {
	if m != nil {
		return m.LastId
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "users_grpc.User")
	proto.RegisterType((*GetUserByIdRequest)(nil), "users_grpc.GetUserByIdRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "users_grpc.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "users_grpc.CreateUserReply")
}

func init() {
	proto.RegisterFile("users_service.proto", fileDescriptor_e2683e726c16c873)
}

var fileDescriptor_e2683e726c16c873 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x6a, 0xdb, 0x40,
	0x14, 0x85, 0x3d, 0xf2, 0xaf, 0xae, 0xa1, 0x3f, 0xd3, 0x42, 0x85, 0x8c, 0x5b, 0xa3, 0x95, 0x29,
	0x54, 0x06, 0x77, 0xd3, 0x2e, 0xdd, 0x06, 0x82, 0xb3, 0xc8, 0x42, 0x49, 0xd6, 0x62, 0xa4, 0xb9,
	0x76, 0x04, 0x92, 0xa5, 0x8c, 0x46, 0x01, 0xbf, 0x4b, 0xde, 0x24, 0xef, 0x90, 0x67, 0x0a, 0x33,
	0xb2, 0x22, 0x19, 0x63, 0x9b, 0x2c, 0xef, 0x3d, 0xe7, 0x30, 0xf7, 0x7c, 0x0c, 0x7c, 0x29, 0x72,
	0x14, 0xb9, 0x9f, 0xa3, 0x78, 0x8c, 0x42, 0x74, 0x33, 0x91, 0xca, 0x94, 0x42, 0xb9, 0x5c, 0x8b,
	0x2c, 0xb4, 0x7f, 0xac, 0xd3, 0x74, 0x1d, 0xe3, 0x4c, 0x2b, 0x41, 0xb1, 0x9a, 0xc9, 0x28, 0xc1,
	0x5c, 0xb2, 0x24, 0x2b, 0xcd, 0xce, 0x8b, 0x01, 0x9d, 0xbb, 0x1c, 0x05, 0xfd, 0x00, 0x46, 0xc4,
	0x2d, 0x32, 0x21, 0x53, 0xd3, 0x33, 0x22, 0x4e, 0xc7, 0x00, 0xab, 0x48, 0xe4, 0xd2, 0xdf, 0xb0,
	0x04, 0x2d, 0x43, 0xef, 0x4d, 0xbd, 0xb9, 0x66, 0x09, 0xd2, 0x11, 0x98, 0x31, 0xab, 0xd4, 0xb6,
	0x56, 0x07, 0x6a, 0xa1, 0x45, 0x1b, 0x06, 0xea, 0x06, 0xad, 0x75, 0x4a, 0xad, 0x9a, 0xe9, 0x57,
	0xe8, 0x62, 0xc2, 0xa2, 0xd8, 0xea, 0x6a, 0xa1, 0x1c, 0xa8, 0x05, 0xfd, 0x80, 0xc5, 0x6c, 0x13,
	0xa2, 0xd5, 0x9b, 0x90, 0x29, 0xf1, 0xaa, 0x91, 0xfe, 0x01, 0x33, 0x88, 0x84, 0xbc, 0xe7, 0x4c,
	0xa2, 0xd5, 0x9f, 0x90, 0xe9, 0x70, 0x6e, 0xbb, 0x65, 0x2b, 0xb7, 0x6a, 0xe5, 0xde, 0x56, 0xad,
	0xbc, 0xda, 0x4c, 0xff, 0x02, 0x84, 0x02, 0x99, 0x44, 0xee, 0x33, 0x69, 0x0d, 0xce, 0x47, 0x77,
	0xee, 0x85, 0x54, 0xd1, 0x22, 0xe3, 0x55, 0xd4, 0x3c, 0x1f, 0xdd, 0xb9, 0x17, 0xd2, 0xf9, 0x05,
	0xf4, 0x12, 0xa5, 0x42, 0xfa, 0x6f, 0xbb, 0xe4, 0x1e, 0x3e, 0x14, 0x98, 0x4b, 0xfa, 0x0d, 0xfa,
	0x8a, 0x80, 0xff, 0x86, 0xb8, 0xa7, 0xc6, 0x25, 0x77, 0x9e, 0x09, 0x7c, 0xfe, 0xaf, 0xdf, 0x55,
	0x91, 0xca, 0xbe, 0x0f, 0x9f, 0x9c, 0x84, 0x6f, 0x9c, 0x80, 0xdf, 0x3e, 0x06, 0xbf, 0xd3, 0x84,
	0xbf, 0x87, 0xb8, 0xfb, 0x0e, 0xc4, 0xce, 0x4f, 0xf8, 0xd8, 0x3c, 0x3e, 0x8b, 0xb7, 0xaa, 0xa9,
	0xbe, 0xad, 0x6e, 0xaa, 0xc6, 0x25, 0x9f, 0x3f, 0x11, 0x18, 0x2a, 0xdb, 0x4d, 0xf9, 0x59, 0xe9,
	0x02, 0x86, 0x35, 0xa8, 0x0b, 0xfa, 0xdd, 0xad, 0xbf, 0xad, 0x7b, 0x48, 0xd0, 0xfe, 0xd4, 0xd4,
	0x95, 0xe8, 0xb4, 0xe8, 0x15, 0x40, 0xfd, 0x3c, 0x1d, 0x37, 0x1d, 0x07, 0x4c, 0xed, 0xd1, 0x31,
	0x39, 0x8b, 0xb7, 0x4e, 0x2b, 0xe8, 0xe9, 0xa6, 0xbf, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4f,
	0xb6, 0x2e, 0x0f, 0x53, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserByID(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/users_grpc.UserService/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/users_grpc.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUserByID(context.Context, *GetUserByIdRequest) (*User, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUserByID(ctx context.Context, req *GetUserByIdRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_grpc.UserService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByID(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_grpc.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users_grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByID",
			Handler:    _UserService_GetUserByID_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_service.proto",
}
