## prometheus.yml ##

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

#rule_files:
#  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'packt-users'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
       - targets: ['127.0.0.1:8000']
         labels:
          group: 'packt-users'

