version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - auction-house

  mongodb:
    image: mongo
    container_name: mongodb_database
    ports:
      - '27017:27017'
    volumes:
      - mongodb_database:/data/db
    networks:
      - auction-house

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/deploy/Dockerfile
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
      - mongodb
    networks:
      - auction-house

volumes:
  api:
  database_postgres:
  mongodb_database:

networks:
  auction-house: