version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-72-238-22.compute-1.amazonaws.com
            database: dc4ff2s2cjsciq
            user: tkdteziahseups
            password: af304dfee9fd44d3fe6fa11e5978a8932bb07a83bcaf8709b2828a827fae39b3
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true