// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addresses_service.proto

package candyland_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Complements int32

const (
	Complements_HOUSE     Complements = 0
	Complements_APARTMENT Complements = 1
)

var Complements_name = map[int32]string{
	0: "HOUSE",
	1: "APARTMENT",
}

var Complements_value = map[string]int32{
	"HOUSE":     0,
	"APARTMENT": 1,
}

func (x Complements) String() string {
	return proto.EnumName(Complements_name, int32(x))
}

func (Complements) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17a4f0d337d6c9c0, []int{0}
}

type Address struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Country              string      `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	State                string      `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	City                 string      `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Street               string      `protobuf:"bytes,6,opt,name=street,proto3" json:"street,omitempty"`
	Number               string      `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	Complement           Complements `protobuf:"varint,8,opt,name=complement,proto3,enum=candyland.grpc.Complements" json:"complement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4f0d337d6c9c0, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Address) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Address) GetComplement() Complements {
	if m != nil {
		return m.Complement
	}
	return Complements_HOUSE
}

type CreateAddressRequest struct {
	CountryId            string      `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	UserId               string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StateId              string      `protobuf:"bytes,3,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CityId               string      `protobuf:"bytes,4,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	StreetId             string      `protobuf:"bytes,5,opt,name=street_id,json=streetId,proto3" json:"street_id,omitempty"`
	Number               string      `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	Complement           Complements `protobuf:"varint,7,opt,name=complement,proto3,enum=candyland.grpc.Complements" json:"complement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAddressRequest) Reset()         { *m = CreateAddressRequest{} }
func (m *CreateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAddressRequest) ProtoMessage()    {}
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4f0d337d6c9c0, []int{1}
}

func (m *CreateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAddressRequest.Unmarshal(m, b)
}
func (m *CreateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAddressRequest.Marshal(b, m, deterministic)
}
func (m *CreateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAddressRequest.Merge(m, src)
}
func (m *CreateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAddressRequest.Size(m)
}
func (m *CreateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAddressRequest proto.InternalMessageInfo

func (m *CreateAddressRequest) GetCountryId() string {
	if m != nil {
		return m.CountryId
	}
	return ""
}

func (m *CreateAddressRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateAddressRequest) GetStateId() string {
	if m != nil {
		return m.StateId
	}
	return ""
}

func (m *CreateAddressRequest) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *CreateAddressRequest) GetStreetId() string {
	if m != nil {
		return m.StreetId
	}
	return ""
}

func (m *CreateAddressRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CreateAddressRequest) GetComplement() Complements {
	if m != nil {
		return m.Complement
	}
	return Complements_HOUSE
}

type CreateAddressReply struct {
	WasCreated           bool     `protobuf:"varint,1,opt,name=wasCreated,proto3" json:"wasCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAddressReply) Reset()         { *m = CreateAddressReply{} }
func (m *CreateAddressReply) String() string { return proto.CompactTextString(m) }
func (*CreateAddressReply) ProtoMessage()    {}
func (*CreateAddressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4f0d337d6c9c0, []int{2}
}

func (m *CreateAddressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAddressReply.Unmarshal(m, b)
}
func (m *CreateAddressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAddressReply.Marshal(b, m, deterministic)
}
func (m *CreateAddressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAddressReply.Merge(m, src)
}
func (m *CreateAddressReply) XXX_Size() int {
	return xxx_messageInfo_CreateAddressReply.Size(m)
}
func (m *CreateAddressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAddressReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAddressReply proto.InternalMessageInfo

func (m *CreateAddressReply) GetWasCreated() bool {
	if m != nil {
		return m.WasCreated
	}
	return false
}

func init() {
	proto.RegisterEnum("candyland.grpc.Complements", Complements_name, Complements_value)
	proto.RegisterType((*Address)(nil), "candyland.grpc.Address")
	proto.RegisterType((*CreateAddressRequest)(nil), "candyland.grpc.CreateAddressRequest")
	proto.RegisterType((*CreateAddressReply)(nil), "candyland.grpc.CreateAddressReply")
}

func init() {
	proto.RegisterFile("addresses_service.proto", fileDescriptor_17a4f0d337d6c9c0)
}

var fileDescriptor_17a4f0d337d6c9c0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0x2b, 0xd7, 0xd6, 0x9f, 0x29, 0x36, 0x66, 0x30, 0xf5, 0xb6, 0xa6, 0xc5, 0x98, 0x42,
	0x4d, 0x0f, 0x3a, 0xb8, 0xbd, 0xf5, 0x24, 0x8c, 0xa1, 0x3a, 0xb4, 0x0d, 0xb2, 0x73, 0xc8, 0xc9,
	0xc8, 0xda, 0x25, 0x08, 0xf4, 0x2f, 0xbb, 0xab, 0x04, 0x3d, 0x6f, 0x5e, 0x21, 0x0f, 0x10, 0x76,
	0xd7, 0x36, 0x72, 0x12, 0x1c, 0x72, 0xd3, 0xf7, 0x7d, 0xa3, 0xd1, 0xfc, 0x46, 0x03, 0xe3, 0x98,
	0x52, 0xce, 0x84, 0x60, 0x62, 0x2b, 0x18, 0xbf, 0x4d, 0x13, 0xe6, 0x57, 0xbc, 0x94, 0x25, 0x0e,
	0x92, 0xb8, 0xa0, 0x4d, 0x16, 0x17, 0xd4, 0xbf, 0xe6, 0x55, 0x32, 0xbb, 0xb7, 0xc0, 0x09, 0x4c,
	0x2d, 0x0e, 0xa0, 0x93, 0x52, 0x62, 0x4d, 0xad, 0xb9, 0x17, 0x75, 0x52, 0x8a, 0x63, 0x70, 0x6a,
	0xc1, 0xf8, 0x36, 0xa5, 0xa4, 0xa3, 0x4d, 0x5b, 0xc9, 0x90, 0x22, 0x01, 0x27, 0x29, 0xeb, 0x42,
	0xf2, 0x86, 0xbc, 0xd7, 0xc1, 0x41, 0xe2, 0x08, 0x7a, 0x42, 0xc6, 0x92, 0x91, 0xae, 0xf6, 0x8d,
	0x40, 0x84, 0x6e, 0x92, 0xca, 0x86, 0xf4, 0xb4, 0xa9, 0x9f, 0xf1, 0x23, 0xd8, 0x42, 0x72, 0xc6,
	0x24, 0xb1, 0x4d, 0x6f, 0xa3, 0x94, 0x5f, 0xd4, 0xf9, 0x8e, 0x71, 0xe2, 0x18, 0xdf, 0x28, 0xfc,
	0x0d, 0x90, 0x94, 0x79, 0x95, 0xb1, 0x9c, 0x15, 0x92, 0xb8, 0x53, 0x6b, 0x3e, 0x58, 0x4c, 0xfc,
	0x53, 0x1a, 0x7f, 0x79, 0xac, 0x10, 0x51, 0xab, 0x7c, 0xf6, 0x60, 0xc1, 0x68, 0xc9, 0x59, 0x2c,
	0xd9, 0x9e, 0x35, 0x62, 0x37, 0x35, 0x13, 0x12, 0xbf, 0xa8, 0xae, 0x7a, 0xf4, 0xed, 0x11, 0xdd,
	0xdb, 0x3b, 0xe1, 0x99, 0x0d, 0x7c, 0x02, 0x57, 0xa3, 0xa9, 0x64, 0xbf, 0x02, 0xad, 0xcd, 0x3b,
	0x0a, 0x50, 0x25, 0x66, 0x09, 0xb6, 0x92, 0x21, 0xc5, 0x09, 0x78, 0x86, 0x51, 0x45, 0x66, 0x15,
	0xae, 0x31, 0x42, 0xda, 0xc2, 0xb6, 0xcf, 0x60, 0x3b, 0x6f, 0xc3, 0xfe, 0x05, 0xf8, 0x84, 0xba,
	0xca, 0x1a, 0xfc, 0x0a, 0x70, 0x17, 0x0b, 0x13, 0x18, 0x66, 0x37, 0x6a, 0x39, 0x3f, 0xbe, 0xc3,
	0x87, 0x56, 0x43, 0xf4, 0xa0, 0xf7, 0xe7, 0xff, 0xe5, 0x7a, 0x35, 0x7c, 0x87, 0x7d, 0xf0, 0x82,
	0x8b, 0x20, 0xda, 0xfc, 0x5d, 0xfd, 0xdb, 0x0c, 0xad, 0x45, 0x0e, 0xc3, 0xe0, 0x70, 0x66, 0x6b,
	0x73, 0x65, 0x78, 0x05, 0xfd, 0x93, 0x4f, 0xe2, 0xb7, 0x67, 0xc3, 0xbe, 0xf0, 0x1f, 0x3e, 0xcf,
	0x5e, 0xa9, 0xaa, 0xb2, 0x66, 0x67, 0xeb, 0x0b, 0xfe, 0xf9, 0x18, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x1b, 0xad, 0xbc, 0xdc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddressesServiceClient is the client API for AddressesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressesServiceClient interface {
	CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressReply, error)
}

type addressesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressesServiceClient(cc grpc.ClientConnInterface) AddressesServiceClient {
	return &addressesServiceClient{cc}
}

func (c *addressesServiceClient) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressReply, error) {
	out := new(CreateAddressReply)
	err := c.cc.Invoke(ctx, "/candyland.grpc.AddressesService/CreateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressesServiceServer is the server API for AddressesService service.
type AddressesServiceServer interface {
	CreateAddress(context.Context, *CreateAddressRequest) (*CreateAddressReply, error)
}

// UnimplementedAddressesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddressesServiceServer struct {
}

func (*UnimplementedAddressesServiceServer) CreateAddress(ctx context.Context, req *CreateAddressRequest) (*CreateAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}

func RegisterAddressesServiceServer(s *grpc.Server, srv AddressesServiceServer) {
	s.RegisterService(&_AddressesService_serviceDesc, srv)
}

func _AddressesService_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressesServiceServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candyland.grpc.AddressesService/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressesServiceServer).CreateAddress(ctx, req.(*CreateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candyland.grpc.AddressesService",
	HandlerType: (*AddressesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAddress",
			Handler:    _AddressesService_CreateAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addresses_service.proto",
}
