// Code generated by protoc-gen-go. DO NOT EDIT.
// source: carts_service.proto

package candyland_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cart struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_19513e58b0c6f32c, []int{0}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Cart) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddProductToCartRequest struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductToCartRequest) Reset()         { *m = AddProductToCartRequest{} }
func (m *AddProductToCartRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductToCartRequest) ProtoMessage()    {}
func (*AddProductToCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19513e58b0c6f32c, []int{1}
}

func (m *AddProductToCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductToCartRequest.Unmarshal(m, b)
}
func (m *AddProductToCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductToCartRequest.Marshal(b, m, deterministic)
}
func (m *AddProductToCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductToCartRequest.Merge(m, src)
}
func (m *AddProductToCartRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductToCartRequest.Size(m)
}
func (m *AddProductToCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductToCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductToCartRequest proto.InternalMessageInfo

func (m *AddProductToCartRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

func (m *AddProductToCartRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddProductToCartRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddProductToCartReply struct {
	WasCreated           bool     `protobuf:"varint,1,opt,name=wasCreated,proto3" json:"wasCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductToCartReply) Reset()         { *m = AddProductToCartReply{} }
func (m *AddProductToCartReply) String() string { return proto.CompactTextString(m) }
func (*AddProductToCartReply) ProtoMessage()    {}
func (*AddProductToCartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_19513e58b0c6f32c, []int{2}
}

func (m *AddProductToCartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductToCartReply.Unmarshal(m, b)
}
func (m *AddProductToCartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductToCartReply.Marshal(b, m, deterministic)
}
func (m *AddProductToCartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductToCartReply.Merge(m, src)
}
func (m *AddProductToCartReply) XXX_Size() int {
	return xxx_messageInfo_AddProductToCartReply.Size(m)
}
func (m *AddProductToCartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductToCartReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductToCartReply proto.InternalMessageInfo

func (m *AddProductToCartReply) GetWasCreated() bool {
	if m != nil {
		return m.WasCreated
	}
	return false
}

func init() {
	proto.RegisterType((*Cart)(nil), "candyland.grpc.Cart")
	proto.RegisterType((*AddProductToCartRequest)(nil), "candyland.grpc.AddProductToCartRequest")
	proto.RegisterType((*AddProductToCartReply)(nil), "candyland.grpc.AddProductToCartReply")
}

func init() {
	proto.RegisterFile("carts_service.proto", fileDescriptor_19513e58b0c6f32c)
}

var fileDescriptor_19513e58b0c6f32c = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4e, 0x2c, 0x2a,
	0x29, 0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4b, 0x4e, 0xcc, 0x4b, 0xa9, 0xcc, 0x49, 0xcc, 0x4b, 0xd1, 0x4b, 0x2f, 0x2a, 0x48, 0x56,
	0x0a, 0xe4, 0x62, 0x71, 0x4e, 0x2c, 0x2a, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe5, 0xe2, 0x2a, 0x28, 0xca, 0x4f, 0x29,
	0x4d, 0x2e, 0x89, 0xcf, 0x4c, 0x91, 0x60, 0x02, 0x8b, 0x73, 0x42, 0x45, 0x3c, 0x53, 0x84, 0xa4,
	0xb8, 0x38, 0x0a, 0x4b, 0x13, 0xf3, 0x4a, 0x32, 0x4b, 0x2a, 0x25, 0x98, 0x15, 0x18, 0x35, 0x58,
	0x83, 0xe0, 0x7c, 0xa5, 0x5c, 0x2e, 0x71, 0xc7, 0x94, 0x94, 0x00, 0x88, 0xda, 0x90, 0x7c, 0x90,
	0xf1, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xe2, 0x5c, 0xec, 0x20, 0x47, 0xc5, 0xc3,
	0xad, 0x62, 0x03, 0x71, 0x3d, 0x29, 0xb2, 0xce, 0x9c, 0x4b, 0x14, 0xd3, 0xba, 0x82, 0x9c, 0x4a,
	0x21, 0x39, 0x2e, 0xae, 0xf2, 0xc4, 0x62, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0x54, 0x88, 0x7d, 0x1c,
	0x41, 0x48, 0x22, 0x46, 0x45, 0x5c, 0x3c, 0x20, 0xc5, 0xc5, 0xc1, 0x90, 0x00, 0x12, 0x4a, 0xe2,
	0x12, 0x40, 0x37, 0x48, 0x48, 0x5d, 0x0f, 0x35, 0xbc, 0xf4, 0x70, 0xf8, 0x4c, 0x4a, 0x95, 0xb0,
	0xc2, 0x82, 0x9c, 0xca, 0x24, 0x36, 0x70, 0x2c, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c,
	0x7b, 0x3f, 0x03, 0x9c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CartsServiceClient is the client API for CartsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CartsServiceClient interface {
	AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartReply, error)
}

type cartsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartsServiceClient(cc grpc.ClientConnInterface) CartsServiceClient {
	return &cartsServiceClient{cc}
}

func (c *cartsServiceClient) AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartReply, error) {
	out := new(AddProductToCartReply)
	err := c.cc.Invoke(ctx, "/candyland.grpc.CartsService/AddProductToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartsServiceServer is the server API for CartsService service.
type CartsServiceServer interface {
	AddProductToCart(context.Context, *AddProductToCartRequest) (*AddProductToCartReply, error)
}

// UnimplementedCartsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCartsServiceServer struct {
}

func (*UnimplementedCartsServiceServer) AddProductToCart(ctx context.Context, req *AddProductToCartRequest) (*AddProductToCartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductToCart not implemented")
}

func RegisterCartsServiceServer(s *grpc.Server, srv CartsServiceServer) {
	s.RegisterService(&_CartsService_serviceDesc, srv)
}

func _CartsService_AddProductToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartsServiceServer).AddProductToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candyland.grpc.CartsService/AddProductToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartsServiceServer).AddProductToCart(ctx, req.(*AddProductToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CartsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candyland.grpc.CartsService",
	HandlerType: (*CartsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProductToCart",
			Handler:    _CartsService_AddProductToCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "carts_service.proto",
}
