// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders_service.proto

package candyland_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a1559d8e098c52, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateOrderRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a1559d8e098c52, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateOrderRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type CreateOrderReply struct {
	WasCreated           bool     `protobuf:"varint,1,opt,name=was_created,json=wasCreated,proto3" json:"was_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReply) Reset()         { *m = CreateOrderReply{} }
func (m *CreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReply) ProtoMessage()    {}
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a1559d8e098c52, []int{2}
}

func (m *CreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReply.Unmarshal(m, b)
}
func (m *CreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReply.Marshal(b, m, deterministic)
}
func (m *CreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReply.Merge(m, src)
}
func (m *CreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReply.Size(m)
}
func (m *CreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReply proto.InternalMessageInfo

func (m *CreateOrderReply) GetWasCreated() bool {
	if m != nil {
		return m.WasCreated
	}
	return false
}

func init() {
	proto.RegisterType((*Order)(nil), "candyland.grpc.Order")
	proto.RegisterType((*CreateOrderRequest)(nil), "candyland.grpc.CreateOrderRequest")
	proto.RegisterType((*CreateOrderReply)(nil), "candyland.grpc.CreateOrderReply")
}

func init() {
	proto.RegisterFile("orders_service.proto", fileDescriptor_b8a1559d8e098c52)
}

var fileDescriptor_b8a1559d8e098c52 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xd0, 0x6a, 0x27, 0x58, 0x64, 0x2c, 0x58, 0x0a, 0x62, 0xc8, 0x29, 0xa7, 0x1c,
	0xda, 0x5f, 0x20, 0x9e, 0x0a, 0x82, 0x92, 0xe2, 0x39, 0xac, 0x3b, 0x83, 0x04, 0x42, 0xb3, 0xce,
	0x24, 0x96, 0xfc, 0x7b, 0xd9, 0x8d, 0x88, 0xb5, 0xd0, 0xe3, 0xbe, 0xf7, 0xed, 0xc7, 0xdb, 0x85,
	0x79, 0x2b, 0xc4, 0xa2, 0x95, 0xb2, 0x7c, 0xd5, 0x96, 0x0b, 0x27, 0x6d, 0xd7, 0xe2, 0xcc, 0x9a,
	0x1d, 0x0d, 0x8d, 0xd9, 0x51, 0xf1, 0x21, 0xce, 0x2e, 0x6f, 0x7b, 0x3d, 0x82, 0xb2, 0x47, 0xb8,
	0x78, 0xf1, 0x97, 0x71, 0x06, 0x71, 0x4d, 0x8b, 0x28, 0x8d, 0xf2, 0x69, 0x19, 0xd7, 0x84, 0x39,
	0x9c, 0x7b, 0x7e, 0x11, 0xa7, 0x51, 0x9e, 0xac, 0xe6, 0xc5, 0xa1, 0xac, 0x78, 0x53, 0x96, 0x32,
	0x10, 0xd9, 0x33, 0xe0, 0x93, 0xb0, 0xe9, 0x38, 0x88, 0x4a, 0xfe, 0xec, 0x59, 0x3b, 0xbc, 0x83,
	0x4b, 0xdf, 0x56, 0xbf, 0xd2, 0x89, 0x3f, 0x6e, 0x08, 0xef, 0x01, 0x9c, 0xb4, 0xd4, 0xdb, 0xce,
	0x77, 0x71, 0xe8, 0xa6, 0x3f, 0xc9, 0x86, 0xb2, 0x35, 0xdc, 0x1c, 0xd8, 0x5c, 0x33, 0xe0, 0x03,
	0x24, 0x7b, 0xa3, 0x95, 0x0d, 0xf9, 0xe8, 0xbb, 0x2a, 0x61, 0x6f, 0x74, 0x24, 0x69, 0x45, 0x70,
	0x1d, 0x70, 0xdd, 0x8e, 0x8f, 0xc3, 0x2d, 0x24, 0x7f, 0x2c, 0x98, 0xfd, 0x9f, 0x7f, 0x3c, 0x78,
	0x99, 0x9e, 0x64, 0x5c, 0x33, 0xbc, 0x9e, 0xbd, 0x4f, 0xc2, 0xa7, 0xad, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xdb, 0x8b, 0xb4, 0x26, 0x71, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrdersServiceClient is the client API for OrdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdersServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
}

type ordersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersServiceClient(cc grpc.ClientConnInterface) OrdersServiceClient {
	return &ordersServiceClient{cc}
}

func (c *ordersServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, "/candyland.grpc.OrdersService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersServiceServer is the server API for OrdersService service.
type OrdersServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
}

// UnimplementedOrdersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrdersServiceServer struct {
}

func (*UnimplementedOrdersServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrdersServiceServer(s *grpc.Server, srv OrdersServiceServer) {
	s.RegisterService(&_OrdersService_serviceDesc, srv)
}

func _OrdersService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/candyland.grpc.OrdersService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrdersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "candyland.grpc.OrdersService",
	HandlerType: (*OrdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrdersService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders_service.proto",
}
